name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      versionName:
        description: "Version Name"
        required: true
      rollout:
        description: "Rollout %"
        required: true
      production:
        description: "Please type production to confirm"
        required: true

jobs:
  deploy:

    runs-on: ubuntu-latest

    if: github.event.inputs.production == 'production'

    steps:
      - uses: actions/checkout@v2

      # Decode our base64-encoded keystore contents from Github Secrets and write it
      # to a temp file that we'll use in Fastlane to sign our app bundle.
      - name: Create upload keystore
        shell: bash
        env:
          KEYSTORE_CONTENTS: ${{ secrets.UPLOAD_KEY_JKS_BASE_64 }}
        run: |
          echo "$KEYSTORE_CONTENTS" | base64 --decode > "$RUNNER_TEMP/upload-key.jks"

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - uses: maierj/fastlane-action@v2.0.1
        with:
          lane: 'deployProduction'
        env:
          VERSION_NAME: ${{ github.event.inputs.versionName }}
          ROLLOUT: ${{ github.event.inputs.rollout }}
          UPLOAD_KEY_DIR: ${{ runner.temp }}
          UPLOAD_KEY_FILENAME: "upload-key.jks"
          SIGNING_STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          SIGNING_KEY_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
          PLAY_STORE_SERVICE_ACCOUNT_JSON: ${{ secrets.PLAY_STORE_API_KEY }}

  on-failed-deploy:
    runs-on: ubuntu-latest
    if: github.event.inputs.production != 'production'
    steps:
      - name: Failed to confirm deployment
        shell: bash
        run: |
          echo "Failed to confirm. You must type 'production' to run this workflow."