name: Android CI

on:
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
    - name: Build with Gradle
      run: ./gradlew assembleDebug
