name: Query version codes

on: workflow_dispatch

jobs:
  query-version-codes:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - uses: maierj/fastlane-action@v2.0.1
        with:
          lane: 'getNextVersionCode'
        env:
          PLAY_STORE_SERVICE_ACCOUNT_JSON: ${{ secrets.PLAY_STORE_API_KEY }}
