name: Release to Internal Play Store Track

on: workflow_dispatch

jobs:
  release-internal:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Write Play Store API Key to temp file
        shell: bash
        env:
          API_KEY: ${{ secrets.PLAY_STORE_API_KEY }}
        run: |
          echo "$API_KEY" >> play-store-api-key.json

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - uses: maierj/fastlane-action@v2.0.1
        with:
          lane: 'deployInternal'
